// <auto-generated />
using System;
using BrewCrewDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BrewCrewDB.Migrations
{
    [DbContext(typeof(BrewCrewContext))]
    partial class BrewCrewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BrewCrewDB.Models.Admin", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            password = "password",
                            username = "admin"
                        });
                });

            modelBuilder.Entity("BrewCrewDB.Models.Beer", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<double>("ABV")
                        .HasColumnType("double precision");

                    b.Property<string>("BreweryID")
                        .HasColumnType("text");

                    b.Property<short>("IBU")
                        .HasColumnType("smallint");

                    b.Property<int>("Keg")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BreweryID");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            ABV = 9.1999999999999993,
                            BreweryID = "eb9300b3-3ff9-42a0-9968-a50d0c882e0e",
                            IBU = (short)33,
                            Keg = 100,
                            Name = "Beer",
                            Price = 4.0,
                            Type = "stout"
                        });
                });

            modelBuilder.Entity("BrewCrewDB.Models.Brewery", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<short>("Zip")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            ID = "eb9300b3-3ff9-42a0-9968-a50d0c882e0e",
                            Address = "123 Beer Lane",
                            City = "East Helena",
                            Name = "Missouri River Brewing Company",
                            State = "MT",
                            Zip = (short)12345
                        },
                        new
                        {
                            ID = "3f855e2f-394e-4bb2-beab-0b751b892194",
                            Address = "123 Stout Lane",
                            City = "Helena",
                            Name = "Lewis and Clark Brewery",
                            State = "MT",
                            Zip = (short)12345
                        },
                        new
                        {
                            ID = "89d7e7a2-182f-4241-865a-912d67dedebd",
                            Address = "123 Ale Lane",
                            City = "Helena",
                            Name = "Bridger Brewing",
                            State = "MT",
                            Zip = (short)12345
                        });
                });

            modelBuilder.Entity("BrewCrewDB.Models.BreweryManager", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("BreweryID")
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BreweryID");

                    b.HasIndex("UserID");

                    b.ToTable("BreweryManagers");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            BreweryID = "eb9300b3-3ff9-42a0-9968-a50d0c882e0e",
                            UserID = "1"
                        },
                        new
                        {
                            ID = "2",
                            BreweryID = "3f855e2f-394e-4bb2-beab-0b751b892194",
                            UserID = "2"
                        },
                        new
                        {
                            ID = "3",
                            BreweryID = "89d7e7a2-182f-4241-865a-912d67dedebd",
                            UserID = "3"
                        });
                });

            modelBuilder.Entity("BrewCrewDB.Models.LineItem", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("BeerID")
                        .HasColumnType("text");

                    b.Property<string>("OrderID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BeerID");

                    b.HasIndex("OrderID");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("BrewCrewDB.Models.Order", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("BreweryID")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short>("TableNumber")
                        .HasColumnType("smallint");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BreweryID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BrewCrewDB.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FName")
                        .HasColumnType("text");

                    b.Property<string>("LName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            Email = "manager1@email.net",
                            FName = "Michael",
                            LName = "Scott",
                            Password = "password",
                            Type = "manager"
                        },
                        new
                        {
                            ID = "2",
                            Email = "manager2@email.net",
                            FName = "Dwight",
                            LName = "Schrute",
                            Password = "password",
                            Type = "manager"
                        },
                        new
                        {
                            ID = "3",
                            Email = "manager3@email.net",
                            FName = "Jim",
                            LName = "Halpert",
                            Password = "password",
                            Type = "manager"
                        });
                });

            modelBuilder.Entity("BrewCrewDB.Models.Beer", b =>
                {
                    b.HasOne("BrewCrewDB.Models.Brewery", null)
                        .WithMany("Beers")
                        .HasForeignKey("BreweryID");
                });

            modelBuilder.Entity("BrewCrewDB.Models.BreweryManager", b =>
                {
                    b.HasOne("BrewCrewDB.Models.Brewery", null)
                        .WithMany("BreweryManagers")
                        .HasForeignKey("BreweryID");

                    b.HasOne("BrewCrewDB.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("BrewCrewDB.Models.LineItem", b =>
                {
                    b.HasOne("BrewCrewDB.Models.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerID");

                    b.HasOne("BrewCrewDB.Models.Order", null)
                        .WithMany("LineItems")
                        .HasForeignKey("OrderID");
                });

            modelBuilder.Entity("BrewCrewDB.Models.Order", b =>
                {
                    b.HasOne("BrewCrewDB.Models.Brewery", null)
                        .WithMany("Orders")
                        .HasForeignKey("BreweryID");

                    b.HasOne("BrewCrewDB.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
